const countriesData = [
  { "name": { "common": "Cook Islands" }, "currencies": { "CKD": { "name": "Cook Islands dollar", "symbol": "$" }, "NZD": { "name": "New Zealand dollar", "symbol": "$" } } },
  { "name": { "common": "Guinea" }, "currencies": { "GNF": { "name": "Guinean franc", "symbol": "Fr" } } },
  { "name": { "common": "Christmas Island" }, "currencies": { "AUD": { "name": "Australian dollar", "symbol": "$" } } },
  { "name": { "common": "Togo" }, "currencies": { "XOF": { "name": "West African CFA franc", "symbol": "Fr" } } },
  { "name": { "common": "Taiwan" }, "currencies": { "TWD": { "name": "New Taiwan dollar", "symbol": "$" } } },
  { "name": { "common": "Kyrgyzstan" }, "currencies": { "KGS": { "name": "Kyrgyzstani som", "symbol": "с" } } },
  { "name": { "common": "Suriname" }, "currencies": { "SRD": { "name": "Surinamese dollar", "symbol": "$" } } },
  { "name": { "common": "Dominican Republic" }, "currencies": { "DOP": { "name": "Dominican peso", "symbol": "$" } } },
  { "name": { "common": "Guatemala" }, "currencies": { "GTQ": { "name": "Guatemalan quetzal", "symbol": "Q" } } },
  { "name": { "common": "Algeria" }, "currencies": { "DZD": { "name": "Algerian dinar", "symbol": "د.ج" } } },
  { "name": { "common": "Ukraine" }, "currencies": { "UAH": { "name": "Ukrainian hryvnia", "symbol": "₴" } } },
  { "name": { "common": "Saint Kitts and Nevis" }, "currencies": { "XCD": { "name": "Eastern Caribbean dollar", "symbol": "$" } } },
  { "name": { "common": "Croatia" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Equatorial Guinea" }, "currencies": { "XAF": { "name": "Central African CFA franc", "symbol": "Fr" } } },
  { "name": { "common": "Panama" }, "currencies": { "PAB": { "name": "Panamanian balboa", "symbol": "B/." }, "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "Belgium" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Bouvet Island" }, "currencies": {} },
  { "name": { "common": "Rwanda" }, "currencies": { "RWF": { "name": "Rwandan franc", "symbol": "Fr" } } },
  { "name": { "common": "French Southern and Antarctic Lands" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Cape Verde" }, "currencies": { "CVE": { "name": "Cape Verdean escudo", "symbol": "Esc" } } },
  { "name": { "common": "South Korea" }, "currencies": { "KRW": { "name": "South Korean won", "symbol": "₩" } } },
  { "name": { "common": "Guam" }, "currencies": { "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "Andorra" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Senegal" }, "currencies": { "XOF": { "name": "West African CFA franc", "symbol": "Fr" } } },
  { "name": { "common": "Uruguay" }, "currencies": { "UYU": { "name": "Uruguayan peso", "symbol": "$" } } },
  { "name": { "common": "Republic of the Congo" }, "currencies": { "XAF": { "name": "Central African CFA franc", "symbol": "Fr" } } },
  { "name": { "common": "Namibia" }, "currencies": { "NAD": { "name": "Namibian dollar", "symbol": "$" }, "ZAR": { "name": "South African rand", "symbol": "R" } } },
  { "name": { "common": "Singapore" }, "currencies": { "SGD": { "name": "Singapore dollar", "symbol": "$" } } },
  { "name": { "common": "Finland" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Egypt" }, "currencies": { "EGP": { "name": "Egyptian pound", "symbol": "£" } } },
  { "name": { "common": "Palau" }, "currencies": { "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "American Samoa" }, "currencies": { "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "Antigua and Barbuda" }, "currencies": { "XCD": { "name": "Eastern Caribbean dollar", "symbol": "$" } } },
  { "name": { "common": "Seychelles" }, "currencies": { "SCR": { "name": "Seychellois rupee", "symbol": "₨" } } },
  { "name": { "common": "Kuwait" }, "currencies": { "KWD": { "name": "Kuwaiti dinar", "symbol": "د.ك" } } },
  { "name": { "common": "Greece" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Kiribati" }, "currencies": { "AUD": { "name": "Australian dollar", "symbol": "$" }, "KID": { "name": "Kiribati dollar", "symbol": "$" } } },
  { "name": { "common": "Cyprus" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Mali" }, "currencies": { "XOF": { "name": "West African CFA franc", "symbol": "Fr" } } },
  { "name": { "common": "Bermuda" }, "currencies": { "BMD": { "name": "Bermudian dollar", "symbol": "$" } } },
  { "name": { "common": "Greenland" }, "currencies": { "DKK": { "name": "krone", "symbol": "kr." } } },
  { "name": { "common": "Eritrea" }, "currencies": { "ERN": { "name": "Eritrean nakfa", "symbol": "Nfk" } } },
  { "name": { "common": "Tanzania" }, "currencies": { "TZS": { "name": "Tanzanian shilling", "symbol": "Sh" } } },
  { "name": { "common": "Vietnam" }, "currencies": { "VND": { "name": "Vietnamese đồng", "symbol": "₫" } } },
  { "name": { "common": "Chad" }, "currencies": { "XAF": { "name": "Central African CFA franc", "symbol": "Fr" } } },
  { "name": { "common": "Ivory Coast" }, "currencies": { "XOF": { "name": "West African CFA franc", "symbol": "Fr" } } },
  { "name": { "common": "Georgia" }, "currencies": { "GEL": { "name": "lari", "symbol": "₾" } } },
  { "name": { "common": "Isle of Man" }, "currencies": { "GBP": { "name": "British pound", "symbol": "£" }, "IMP": { "name": "Manx pound", "symbol": "£" } } },
  { "name": { "common": "South Georgia" }, "currencies": { "GBP": { "name": "British pound", "symbol": "£" } } },
  { "name": { "common": "Bolivia" }, "currencies": { "BOB": { "name": "Bolivian boliviano", "symbol": "Bs." } } },
  { "name": { "common": "United States Minor Outlying Islands" }, "currencies": { "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "Denmark" }, "currencies": { "DKK": { "name": "Danish krone", "symbol": "kr" } } },
  { "name": { "common": "Turkmenistan" }, "currencies": { "TMT": { "name": "Turkmenistan manat", "symbol": "m" } } },
  { "name": { "common": "Niger" }, "currencies": { "XOF": { "name": "West African CFA franc", "symbol": "Fr" } } },
  { "name": { "common": "Micronesia" }, "currencies": { "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "Jersey" }, "currencies": { "GBP": { "name": "British pound", "symbol": "£" }, "JEP": { "name": "Jersey pound", "symbol": "£" } } },
  { "name": { "common": "Cayman Islands" }, "currencies": { "KYD": { "name": "Cayman Islands dollar", "symbol": "$" } } },
  { "name": { "common": "Liechtenstein" }, "currencies": { "CHF": { "name": "Swiss franc", "symbol": "Fr" } } },
  { "name": { "common": "Bosnia and Herzegovina" }, "currencies": { "BAM": { "name": "Bosnia and Herzegovina convertible mark", "symbol": "KM" } } },
  { "name": { "common": "France" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "French Polynesia" }, "currencies": { "XPF": { "name": "CFP franc", "symbol": "₣" } } },
  { "name": { "common": "Kazakhstan" }, "currencies": { "KZT": { "name": "Kazakhstani tenge", "symbol": "₸" } } },
  { "name": { "common": "Angola" }, "currencies": { "AOA": { "name": "Angolan kwanza", "symbol": "Kz" } } },
  { "name": { "common": "New Zealand" }, "currencies": { "NZD": { "name": "New Zealand dollar", "symbol": "$" } } },
  { "name": { "common": "Puerto Rico" }, "currencies": { "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "Saudi Arabia" }, "currencies": { "SAR": { "name": "Saudi riyal", "symbol": "ر.س" } } },
  { "name": { "common": "Montenegro" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "South Africa" }, "currencies": { "ZAR": { "name": "South African rand", "symbol": "R" } } },
  { "name": { "common": "Pakistan" }, "currencies": { "PKR": { "name": "Pakistani rupee", "symbol": "₨" } } },
  { "name": { "common": "Sri Lanka" }, "currencies": { "LKR": { "name": "Sri Lankan rupee", "symbol": "Rs  රු" } } },
  { "name": { "common": "Cameroon" }, "currencies": { "XAF": { "name": "Central African CFA franc", "symbol": "Fr" } } },
  { "name": { "common": "Guernsey" }, "currencies": { "GBP": { "name": "British pound", "symbol": "£" }, "GGP": { "name": "Guernsey pound", "symbol": "£" } } },
  { "name": { "common": "Liberia" }, "currencies": { "LRD": { "name": "Liberian dollar", "symbol": "$" } } },
  { "name": { "common": "United Arab Emirates" }, "currencies": { "AED": { "name": "United Arab Emirates dirham", "symbol": "د.إ" } } },
  { "name": { "common": "Switzerland" }, "currencies": { "CHF": { "name": "Swiss franc", "symbol": "Fr." } } },
  { "name": { "common": "Hungary" }, "currencies": { "HUF": { "name": "Hungarian forint", "symbol": "Ft" } } },
  { "name": { "common": "Libya" }, "currencies": { "LYD": { "name": "Libyan dinar", "symbol": "ل.د" } } },
  { "name": { "common": "Vanuatu" }, "currencies": { "VUV": { "name": "Vanuatu vatu", "symbol": "Vt" } } },
  { "name": { "common": "Wallis and Futuna" }, "currencies": { "XPF": { "name": "CFP franc", "symbol": "₣" } } },
  { "name": { "common": "Saint Lucia" }, "currencies": { "XCD": { "name": "Eastern Caribbean dollar", "symbol": "$" } } },
  { "name": { "common": "Central African Republic" }, "currencies": { "XAF": { "name": "Central African CFA franc", "symbol": "Fr" } } },
  { "name": { "common": "Tajikistan" }, "currencies": { "TJS": { "name": "Tajikistani somoni", "symbol": "ЅМ" } } },
  { "name": { "common": "Ireland" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "New Caledonia" }, "currencies": { "XPF": { "name": "CFP franc", "symbol": "₣" } } },
  { "name": { "common": "Yemen" }, "currencies": { "YER": { "name": "Yemeni rial", "symbol": "﷼" } } },
  { "name": { "common": "Faroe Islands" }, "currencies": { "DKK": { "name": "Danish krone", "symbol": "kr" }, "FOK": { "name": "Faroese króna", "symbol": "kr" } } },
  { "name": { "common": "Cuba" }, "currencies": { "CUC": { "name": "Cuban convertible peso", "symbol": "$" }, "CUP": { "name": "Cuban peso", "symbol": "$" } } },
  { "name": { "common": "Azerbaijan" }, "currencies": { "AZN": { "name": "Azerbaijani manat", "symbol": "₼" } } },
  { "name": { "common": "Solomon Islands" }, "currencies": { "SBD": { "name": "Solomon Islands dollar", "symbol": "$" } } },
  { "name": { "common": "Jamaica" }, "currencies": { "JMD": { "name": "Jamaican dollar", "symbol": "$" } } },
  { "name": { "common": "Morocco" }, "currencies": { "MAD": { "name": "Moroccan dirham", "symbol": "د.م." } } },
  { "name": { "common": "Trinidad and Tobago" }, "currencies": { "TTD": { "name": "Trinidad and Tobago dollar", "symbol": "$" } } },
  { "name": { "common": "Mayotte" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Niue" }, "currencies": { "NZD": { "name": "New Zealand dollar", "symbol": "$" } } },
  { "name": { "common": "Belize" }, "currencies": { "BZD": { "name": "Belize dollar", "symbol": "$" } } },
  { "name": { "common": "China" }, "currencies": { "CNY": { "name": "Chinese yuan", "symbol": "¥" } } },
  { "name": { "common": "Samoa" }, "currencies": { "WST": { "name": "Samoan tālā", "symbol": "T" } } },
  { "name": { "common": "British Virgin Islands" }, "currencies": { "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "Sudan" }, "currencies": { "SDG": { "name": "Sudanese pound", "symbol": "ج.س" } } },
  { "name": { "common": "Norfolk Island" }, "currencies": { "AUD": { "name": "Australian dollar", "symbol": "$" } } },
  { "name": { "common": "Slovakia" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Burundi" }, "currencies": { "BIF": { "name": "Burundian franc", "symbol": "Fr" } } },
  { "name": { "common": "Marshall Islands" }, "currencies": { "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "Austria" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Mozambique" }, "currencies": { "MZN": { "name": "Mozambican metical", "symbol": "MT" } } },
  { "name": { "common": "Saint Vincent and the Grenadines" }, "currencies": { "XCD": { "name": "Eastern Caribbean dollar", "symbol": "$" } } },
  { "name": { "common": "Papua New Guinea" }, "currencies": { "PGK": { "name": "Papua New Guinean kina", "symbol": "K" } } },
  { "name": { "common": "Turkey" }, "currencies": { "TRY": { "name": "Turkish lira", "symbol": "₺" } } },
  { "name": { "common": "Kosovo" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Grenada" }, "currencies": { "XCD": { "name": "Eastern Caribbean dollar", "symbol": "$" } } },
  { "name": { "common": "Cambodia" }, "currencies": { "KHR": { "name": "Cambodian riel", "symbol": "៛" }, "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "Portugal" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "United Kingdom" }, "currencies": { "GBP": { "name": "British pound", "symbol": "£" } } },
  { "name": { "common": "Nigeria" }, "currencies": { "NGN": { "name": "Nigerian naira", "symbol": "₦" } } },
  { "name": { "common": "Anguilla" }, "currencies": { "XCD": { "name": "Eastern Caribbean dollar", "symbol": "$" } } },
  { "name": { "common": "Northern Mariana Islands" }, "currencies": { "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "Israel" }, "currencies": { "ILS": { "name": "Israeli new shekel", "symbol": "₪" } } },
  { "name": { "common": "French Guiana" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Lebanon" }, "currencies": { "LBP": { "name": "Lebanese pound", "symbol": "ل.ل" } } },
  { "name": { "common": "Japan" }, "currencies": { "JPY": { "name": "Japanese yen", "symbol": "¥" } } },
  { "name": { "common": "Gambia" }, "currencies": { "GMD": { "name": "dalasi", "symbol": "D" } } },
  { "name": { "common": "Saint Martin" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Guinea-Bissau" }, "currencies": { "XOF": { "name": "West African CFA franc", "symbol": "Fr" } } },
  { "name": { "common": "Laos" }, "currencies": { "LAK": { "name": "Lao kip", "symbol": "₭" } } },
  { "name": { "common": "North Macedonia" }, "currencies": { "MKD": { "name": "denar", "symbol": "den" } } },
  { "name": { "common": "Qatar" }, "currencies": { "QAR": { "name": "Qatari riyal", "symbol": "ر.ق" } } },
  { "name": { "common": "Zambia" }, "currencies": { "ZMW": { "name": "Zambian kwacha", "symbol": "ZK" } } },
  { "name": { "common": "Barbados" }, "currencies": { "BBD": { "name": "Barbadian dollar", "symbol": "$" } } },
  { "name": { "common": "Vatican City" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Italy" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Comoros" }, "currencies": { "KMF": { "name": "Comorian franc", "symbol": "Fr" } } },
  { "name": { "common": "Albania" }, "currencies": { "ALL": { "name": "Albanian lek", "symbol": "L" } } },
  { "name": { "common": "Gibraltar" }, "currencies": { "GIP": { "name": "Gibraltar pound", "symbol": "£" } } },
  { "name": { "common": "Mongolia" }, "currencies": { "MNT": { "name": "Mongolian tögrög", "symbol": "₮" } } },
  { "name": { "common": "Tonga" }, "currencies": { "TOP": { "name": "Tongan paʻanga", "symbol": "T$" } } },
  { "name": { "common": "Madagascar" }, "currencies": { "MGA": { "name": "Malagasy ariary", "symbol": "Ar" } } },
  { "name": { "common": "Saint Pierre and Miquelon" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Saint Helena, Ascension and Tristan da Cunha" }, "currencies": { "GBP": { "name": "Pound sterling", "symbol": "£" }, "SHP": { "name": "Saint Helena pound", "symbol": "£" } } },
  { "name": { "common": "Monaco" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Brazil" }, "currencies": { "BRL": { "name": "Brazilian real", "symbol": "R$" } } },
  { "name": { "common": "Australia" }, "currencies": { "AUD": { "name": "Australian dollar", "symbol": "$" } } },
  { "name": { "common": "Guyana" }, "currencies": { "GYD": { "name": "Guyanese dollar", "symbol": "$" } } },
  { "name": { "common": "Slovenia" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "San Marino" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Tokelau" }, "currencies": { "NZD": { "name": "New Zealand dollar", "symbol": "$" } } },
  { "name": { "common": "Palestine" }, "currencies": { "EGP": { "name": "Egyptian pound", "symbol": "E£" }, "ILS": { "name": "Israeli new shekel", "symbol": "₪" }, "JOD": { "name": "Jordanian dinar", "symbol": "JD" } } },
  { "name": { "common": "Bhutan" }, "currencies": { "BTN": { "name": "Bhutanese ngultrum", "symbol": "Nu." }, "INR": { "name": "Indian rupee", "symbol": "₹" } } },
  { "name": { "common": "Sint Maarten" }, "currencies": { "ANG": { "name": "Netherlands Antillean guilder", "symbol": "ƒ" } } },
  { "name": { "common": "Philippines" }, "currencies": { "PHP": { "name": "Philippine peso", "symbol": "₱" } } },
  { "name": { "common": "Chile" }, "currencies": { "CLP": { "name": "Chilean peso", "symbol": "$" } } },
  { "name": { "common": "Martinique" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Haiti" }, "currencies": { "HTG": { "name": "Haitian gourde", "symbol": "G" } } },
  { "name": { "common": "Heard Island and McDonald Islands" }, "currencies": {} },
  { "name": { "common": "Antarctica" }, "currencies": {} },
  { "name": { "common": "São Tomé and Príncipe" }, "currencies": { "STN": { "name": "São Tomé and Príncipe dobra", "symbol": "Db" } } },
  { "name": { "common": "Macau" }, "currencies": { "MOP": { "name": "Macanese pataca", "symbol": "P" } } },
  { "name": { "common": "Mauritius" }, "currencies": { "MUR": { "name": "Mauritian rupee", "symbol": "₨" } } },
  { "name": { "common": "Bahrain" }, "currencies": { "BHD": { "name": "Bahraini dinar", "symbol": ".د.ب" } } },
  { "name": { "common": "Mexico" }, "currencies": { "MXN": { "name": "Mexican peso", "symbol": "$" } } },
  { "name": { "common": "Pitcairn Islands" }, "currencies": { "NZD": { "name": "New Zealand dollar", "symbol": "$" } } },
  { "name": { "common": "Argentina" }, "currencies": { "ARS": { "name": "Argentine peso", "symbol": "$" } } },
  { "name": { "common": "Nepal" }, "currencies": { "NPR": { "name": "Nepalese rupee", "symbol": "₨" } } },
  { "name": { "common": "Sweden" }, "currencies": { "SEK": { "name": "Swedish krona", "symbol": "kr" } } },
  { "name": { "common": "Sierra Leone" }, "currencies": { "SLE": { "name": "Leone", "symbol": "Le" } } },
  { "name": { "common": "Eswatini" }, "currencies": { "SZL": { "name": "Swazi lilangeni", "symbol": "L" }, "ZAR": { "name": "South African rand", "symbol": "R" } } },
  { "name": { "common": "Spain" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Colombia" }, "currencies": { "COP": { "name": "Colombian peso", "symbol": "$" } } },
  { "name": { "common": "Turks and Caicos Islands" }, "currencies": { "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "Djibouti" }, "currencies": { "DJF": { "name": "Djiboutian franc", "symbol": "Fr" } } },
  { "name": { "common": "Nauru" }, "currencies": { "AUD": { "name": "Australian dollar", "symbol": "$" } } },
  { "name": { "common": "El Salvador" }, "currencies": { "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "Åland Islands" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Guadeloupe" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Honduras" }, "currencies": { "HNL": { "name": "Honduran lempira", "symbol": "L" } } },
  { "name": { "common": "Kenya" }, "currencies": { "KES": { "name": "Kenyan shilling", "symbol": "Sh" } } },
  { "name": { "common": "Malta" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Latvia" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Gabon" }, "currencies": { "XAF": { "name": "Central African CFA franc", "symbol": "Fr" } } },
  { "name": { "common": "Hong Kong" }, "currencies": { "HKD": { "name": "Hong Kong dollar", "symbol": "$" } } },
  { "name": { "common": "Svalbard and Jan Mayen" }, "currencies": { "NOK": { "name": "krone", "symbol": "kr" } } },
  { "name": { "common": "Tuvalu" }, "currencies": { "AUD": { "name": "Australian dollar", "symbol": "$" }, "TVD": { "name": "Tuvaluan dollar", "symbol": "$" } } },
  { "name": { "common": "Timor-Leste" }, "currencies": { "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "Western Sahara" }, "currencies": { "DZD": { "name": "Algerian dinar", "symbol": "دج" }, "MAD": { "name": "Moroccan dirham", "symbol": "DH" }, "MRU": { "name": "Mauritanian ouguiya", "symbol": "UM" } } },
  { "name": { "common": "Lesotho" }, "currencies": { "LSL": { "name": "Lesotho loti", "symbol": "L" }, "ZAR": { "name": "South African rand", "symbol": "R" } } },
  { "name": { "common": "United States" }, "currencies": { "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "Thailand" }, "currencies": { "THB": { "name": "Thai baht", "symbol": "฿" } } },
  { "name": { "common": "British Indian Ocean Territory" }, "currencies": { "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "India" }, "currencies": { "INR": { "name": "Indian rupee", "symbol": "₹" } } },
  { "name": { "common": "Lithuania" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Montserrat" }, "currencies": { "XCD": { "name": "Eastern Caribbean dollar", "symbol": "$" } } },
  { "name": { "common": "Zimbabwe" }, "currencies": { "ZWL": { "name": "Zimbabwean dollar", "symbol": "$" } } },
  { "name": { "common": "Falkland Islands" }, "currencies": { "FKP": { "name": "Falkland Islands pound", "symbol": "£" } } },
  { "name": { "common": "Maldives" }, "currencies": { "MVR": { "name": "Maldivian rufiyaa", "symbol": ".ރ" } } },
  { "name": { "common": "Tunisia" }, "currencies": { "TND": { "name": "Tunisian dinar", "symbol": "د.ت" } } },
  { "name": { "common": "Estonia" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Bangladesh" }, "currencies": { "BDT": { "name": "Bangladeshi taka", "symbol": "৳" } } },
  { "name": { "common": "Uzbekistan" }, "currencies": { "UZS": { "name": "Uzbekistani soʻm", "symbol": "so'm" } } },
  { "name": { "common": "Ghana" }, "currencies": { "GHS": { "name": "Ghanaian cedi", "symbol": "₵" } } },
  { "name": { "common": "Norway" }, "currencies": { "NOK": { "name": "Norwegian krone", "symbol": "kr" } } },
  { "name": { "common": "Somalia" }, "currencies": { "SOS": { "name": "Somali shilling", "symbol": "Sh" } } },
  { "name": { "common": "Bahamas" }, "currencies": { "BSD": { "name": "Bahamian dollar", "symbol": "$" }, "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "Oman" }, "currencies": { "OMR": { "name": "Omani rial", "symbol": "ر.ع." } } },
  { "name": { "common": "Luxembourg" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Iraq" }, "currencies": { "IQD": { "name": "Iraqi dinar", "symbol": "ع.د" } } },
  { "name": { "common": "United States Virgin Islands" }, "currencies": { "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "Mauritania" }, "currencies": { "MRU": { "name": "Mauritanian ouguiya", "symbol": "UM" } } },
  { "name": { "common": "Canada" }, "currencies": { "CAD": { "name": "Canadian dollar", "symbol": "$" } } },
  { "name": { "common": "Myanmar" }, "currencies": { "MMK": { "name": "Burmese kyat", "symbol": "Ks" } } },
  { "name": { "common": "Malaysia" }, "currencies": { "MYR": { "name": "Malaysian ringgit", "symbol": "RM" } } },
  { "name": { "common": "Cocos (Keeling) Islands" }, "currencies": { "AUD": { "name": "Australian dollar", "symbol": "$" } } },
  { "name": { "common": "Caribbean Netherlands" }, "currencies": { "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "Uganda" }, "currencies": { "UGX": { "name": "Ugandan shilling", "symbol": "Sh" } } },
  { "name": { "common": "Iran" }, "currencies": { "IRR": { "name": "Iranian rial", "symbol": "﷼" } } },
  { "name": { "common": "Curaçao" }, "currencies": { "ANG": { "name": "Netherlands Antillean guilder", "symbol": "ƒ" } } },
  { "name": { "common": "Romania" }, "currencies": { "RON": { "name": "Romanian leu", "symbol": "lei" } } },
  { "name": { "common": "Syria" }, "currencies": { "SYP": { "name": "Syrian pound", "symbol": "£" } } },
  { "name": { "common": "Fiji" }, "currencies": { "FJD": { "name": "Fijian dollar", "symbol": "$" } } },
  { "name": { "common": "Aruba" }, "currencies": { "AWG": { "name": "Aruban florin", "symbol": "ƒ" } } },
  { "name": { "common": "Netherlands" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Peru" }, "currencies": { "PEN": { "name": "Peruvian sol", "symbol": "S/ " } } },
  { "name": { "common": "Réunion" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Botswana" }, "currencies": { "BWP": { "name": "Botswana pula", "symbol": "P" } } },
  { "name": { "common": "Afghanistan" }, "currencies": { "AFN": { "name": "Afghan afghani", "symbol": "؋" } } },
  { "name": { "common": "Serbia" }, "currencies": { "RSD": { "name": "Serbian dinar", "symbol": "дин." } } },
  { "name": { "common": "Czechia" }, "currencies": { "CZK": { "name": "Czech koruna", "symbol": "Kč" } } },
  { "name": { "common": "Dominica" }, "currencies": { "XCD": { "name": "Eastern Caribbean dollar", "symbol": "$" } } },
  { "name": { "common": "Poland" }, "currencies": { "PLN": { "name": "Polish złoty", "symbol": "zł" } } },
  { "name": { "common": "Benin" }, "currencies": { "XOF": { "name": "West African CFA franc", "symbol": "Fr" } } },
  { "name": { "common": "Moldova" }, "currencies": { "MDL": { "name": "Moldovan leu", "symbol": "L" } } },
  { "name": { "common": "Russia" }, "currencies": { "RUB": { "name": "Russian ruble", "symbol": "₽" } } },
  { "name": { "common": "Saint Barthélemy" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Indonesia" }, "currencies": { "IDR": { "name": "Indonesian rupiah", "symbol": "Rp" } } },
  { "name": { "common": "Nicaragua" }, "currencies": { "NIO": { "name": "Nicaraguan córdoba", "symbol": "C$" } } },
  { "name": { "common": "Armenia" }, "currencies": { "AMD": { "name": "Armenian dram", "symbol": "֏" } } },
  { "name": { "common": "Belarus" }, "currencies": { "BYN": { "name": "Belarusian ruble", "symbol": "Br" } } },
  { "name": { "common": "Ethiopia" }, "currencies": { "ETB": { "name": "Ethiopian birr", "symbol": "Br" } } },
  { "name": { "common": "Costa Rica" }, "currencies": { "CRC": { "name": "Costa Rican colón", "symbol": "₡" } } },
  { "name": { "common": "Jordan" }, "currencies": { "JOD": { "name": "Jordanian dinar", "symbol": "د.ا" } } },
  { "name": { "common": "Germany" }, "currencies": { "EUR": { "name": "euro", "symbol": "€" } } },
  { "name": { "common": "Ecuador" }, "currencies": { "USD": { "name": "United States dollar", "symbol": "$" } } },
  { "name": { "common": "North Korea" }, "currencies": { "KPW": { "name": "North Korean won", "symbol": "₩" } } },
  { "name": { "common": "Iceland" }, "currencies": { "ISK": { "name": "Icelandic króna", "symbol": "kr" } } },
  { "name": { "common": "South Sudan" }, "currencies": { "SSP": { "name": "South Sudanese pound", "symbol": "£" } } },
  { "name": { "common": "Malawi" }, "currencies": { "MWK": { "name": "Malawian kwacha", "symbol": "MK" } } },
  { "name": { "common": "Burkina Faso" }, "currencies": { "XOF": { "name": "West African CFA franc", "symbol": "Fr" } } },
  { "name": { "common": "DR Congo" }, "currencies": { "CDF": { "name": "Congolese franc", "symbol": "FC" } } },
  { "name": { "common": "Venezuela" }, "currencies": { "VES": { "name": "Venezuelan bolívar soberano", "symbol": "Bs.S." } } },
  { "name": { "common": "Brunei" }, "currencies": { "BND": { "name": "Brunei dollar", "symbol": "$" }, "SGD": { "name": "Singapore dollar", "symbol": "$" } } },
  { "name": { "common": "Paraguay" }, "currencies": { "PYG": { "name": "Paraguayan guaraní", "symbol": "₲" } } },
  { "name": { "common": "Bulgaria" }, "currencies": { "BGN": { "name": "Bulgarian lev", "symbol": "лв" } } }
];

module.exports = {
  getCurrencyByCountry: (countryName) => {
    const country = countriesData.find(c => c.name.common.toLowerCase() === countryName.toLowerCase());
    if (country && country.currencies) {
      return Object.keys(country.currencies)[0];
    }
    return 'USD';
  }
};
